--remap window management
vim.keymap.set('', 'éu', '<C-w>h', { noremap = true })
vim.keymap.set('', 'ée', '<C-w>l', { noremap = true })
vim.keymap.set('', 'éi', '<C-w>j', { noremap = true })
vim.keymap.set('', 'ép', '<C-w>k', { noremap = true })
vim.keymap.set('', 'éé', '<C-w>p', { noremap = true })
vim.keymap.set('', 'év', '<C-w>v', { noremap = true })
vim.keymap.set('', 'éd', '<C-w>s', { noremap = true })
--remap TSRL to HJKL, lower and upper case
vim.keymap.set('', 't', 'h', { noremap = true })
vim.keymap.set('', 'T', 'H', { noremap = true })
vim.keymap.set('', 's', 'j', { noremap = true })
vim.keymap.set('', 'S', 'J', { noremap = true })
vim.keymap.set('', 'r', 'k', { noremap = true })
vim.keymap.set('', 'R', 'K', { noremap = true })
vim.keymap.set('', 'n', 'l', { noremap = true })
vim.keymap.set('', 'N', 'L', { noremap = true })
-- remap HJKL to CTSR lower and upper case
vim.keymap.set('', 'h', 't', { noremap = true })
vim.keymap.set('', 'H', 'T', { noremap = true })
vim.keymap.set('', 'j', 's', { noremap = true })
vim.keymap.set('', 'J', 'S', { noremap = true })
vim.keymap.set('', 'k', 'r', { noremap = true })
vim.keymap.set('', 'K', 'R', { noremap = true })
vim.keymap.set('', 'l', 'n', { noremap = true })
vim.keymap.set('', 'L', 'N', { noremap = true })
-- remap folding next / previous
vim.keymap.set('', 'zs', 'zj', { noremap = true })
vim.keymap.set('', 'zt', 'zk', { noremap = true })
-- correction ortho
vim.keymap.set('', ']k', ']s', { noremap = true })
vim.keymap.set('', '[k', '[s', { noremap = true })
-- chiffre en accès direct
-- vim.keymap.set('', '"', '1', { noremap = true })
-- vim.keymap.set('', '«', '2', { noremap = true })
-- vim.keymap.set('', '»', '3', { noremap = true })
-- vim.keymap.set('', '(', '4', { noremap = true })
-- vim.keymap.set('', ')', '5', { noremap = true })
-- vim.keymap.set('', '@', '6', { noremap = true })
-- vim.keymap.set('', '+', '7', { noremap = true })
-- vim.keymap.set('', '-', '8', { noremap = true })
-- vim.keymap.set('', '/', '9', { noremap = true })
-- vim.keymap.set('', '*', '0', { noremap = true })
-- vim.keymap.set('', '1', '"', { noremap = true })
-- vim.keymap.set('', '2', '«', { noremap = true })
-- vim.keymap.set('', '3', '»', { noremap = true })
-- vim.keymap.set('', '4', '(', { noremap = true })
-- vim.keymap.set('', '5', ')', { noremap = true })
-- vim.keymap.set('', '6', '@', { noremap = true })
-- vim.keymap.set('', '7', '+', { noremap = true })
-- vim.keymap.set('', '8', '-', { noremap = true })
-- vim.keymap.set('', '9', '/', { noremap = true })
-- vim.keymap.set('', '0', '*', { noremap = true })
-- Leader key mappings
-- vim.keymap.set('n', '<Leader>i', 'vim.lsp.buf.format({async = true})', { noremap = true })
-- Telescope
vim.keymap.set('n', '<Leader>ff', ':Telescope find_files<CR>', { noremap = true })
vim.keymap.set('n', '<Leader>fg', ':Telescope live_grep<CR>', { noremap = true })
vim.keymap.set('n', '<Leader>fb', ':Telescope buffers<CR>', { noremap = true })
vim.keymap.set('n', '<Leader>fh', ':Telescope help_tags<CR>', { noremap = true })
-- Explore
-- vim.keymap.set('n', '<Leader>e', ':Ex<CR>', { noremap = true })
-- Hop
vim.keymap.set('n', '<Leader>hh', ':HopWord<CR>', { noremap = true })
vim.keymap.set('n', '<Leader>hl', ':HopLine<CR>', { noremap = true })
